/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Interfaces;

import Conexion.ConexionDB;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.function.Consumer;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author erick
 */
public class ActualizarFuncionario extends javax.swing.JFrame {

    /**
     * Creates new form ActualizarFuncionario
     */
    public ActualizarFuncionario() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabelTitle = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jTextFieldIdentificacion = new javax.swing.JTextField();
        jButtonConsultar = new javax.swing.JButton();
        jButtonVolver = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jTextFieldNombres = new javax.swing.JTextField();
        jTextFieldApellidos = new javax.swing.JTextField();
        jTextFieldEdad = new javax.swing.JTextField();
        jTextFieldVacuna = new javax.swing.JTextField();
        jTextFieldCategoria = new javax.swing.JTextField();
        jTextFieldCargo = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jLabelFondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabelTitle.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabelTitle.setForeground(new java.awt.Color(255, 255, 255));
        jLabelTitle.setText("Actualizar Funcionario");
        getContentPane().add(jLabelTitle, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 10, -1, -1));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Identificación:");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 110, -1, -1));

        jTextFieldIdentificacion.setBackground(new java.awt.Color(51, 0, 153));
        jTextFieldIdentificacion.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jTextFieldIdentificacion.setForeground(new java.awt.Color(255, 255, 255));
        getContentPane().add(jTextFieldIdentificacion, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 110, 100, -1));

        jButtonConsultar.setBackground(new java.awt.Color(51, 0, 153));
        jButtonConsultar.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jButtonConsultar.setForeground(new java.awt.Color(255, 255, 255));
        jButtonConsultar.setText("Consultar");
        jButtonConsultar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonConsultarActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonConsultar, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 140, 190, 30));

        jButtonVolver.setBackground(new java.awt.Color(51, 0, 153));
        jButtonVolver.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jButtonVolver.setForeground(new java.awt.Color(255, 255, 255));
        jButtonVolver.setText("Volver");
        jButtonVolver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonVolverActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonVolver, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 290, -1, -1));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Nombres");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 100, -1, -1));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Apellidos");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 130, -1, -1));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Edad");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 160, -1, -1));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Vacuna");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 190, -1, -1));

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Categoria");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 220, -1, -1));

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Cargo");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 250, -1, -1));

        jTextFieldNombres.setBackground(new java.awt.Color(51, 0, 153));
        jTextFieldNombres.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jTextFieldNombres.setForeground(new java.awt.Color(255, 255, 255));
        getContentPane().add(jTextFieldNombres, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 100, 90, -1));

        jTextFieldApellidos.setBackground(new java.awt.Color(51, 0, 153));
        jTextFieldApellidos.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jTextFieldApellidos.setForeground(new java.awt.Color(255, 255, 255));
        getContentPane().add(jTextFieldApellidos, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 130, 90, -1));

        jTextFieldEdad.setBackground(new java.awt.Color(51, 0, 153));
        jTextFieldEdad.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jTextFieldEdad.setForeground(new java.awt.Color(255, 255, 255));
        getContentPane().add(jTextFieldEdad, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 160, 90, -1));

        jTextFieldVacuna.setBackground(new java.awt.Color(51, 0, 153));
        jTextFieldVacuna.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jTextFieldVacuna.setForeground(new java.awt.Color(255, 255, 255));
        getContentPane().add(jTextFieldVacuna, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 190, 90, -1));

        jTextFieldCategoria.setBackground(new java.awt.Color(51, 0, 153));
        jTextFieldCategoria.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jTextFieldCategoria.setForeground(new java.awt.Color(255, 255, 255));
        getContentPane().add(jTextFieldCategoria, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 220, 90, -1));

        jTextFieldCargo.setBackground(new java.awt.Color(51, 0, 153));
        jTextFieldCargo.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jTextFieldCargo.setForeground(new java.awt.Color(255, 255, 255));
        getContentPane().add(jTextFieldCargo, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 250, 90, -1));

        jButton1.setBackground(new java.awt.Color(51, 0, 153));
        jButton1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("Guardar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 210, 190, 60));

        jLabelFondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/BlueWallpaper.png"))); // NOI18N
        getContentPane().add(jLabelFondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 410, 330));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonVolverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonVolverActionPerformed
        // TODO add your handling code here:
        this.dispose();
	Menu menu = new Menu();
        menu.setVisible(true);
    }//GEN-LAST:event_jButtonVolverActionPerformed

    private void jButtonConsultarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonConsultarActionPerformed
        // TODO add your handling code here:
                String documento = jTextFieldIdentificacion.getText();
        if ("".equals(documento)) {
            JOptionPane.showMessageDialog(null, "Ingrese su cédula");
        }
        else {
            try {
                ConexionDB cone = new ConexionDB();
                cone.establecerconexion();
                Statement stam = cone.con.createStatement();
                ResultSet rtaset = stam.executeQuery("SELECT * FROM funcionario WHERE cedula='"+documento+"'");
                if (rtaset.next()) {
                    jTextFieldNombres.setText(rtaset.getString("nombres"));
                    jTextFieldApellidos.setText(rtaset.getString("apellidos"));
                    jTextFieldEdad.setText(rtaset.getString("edad"));
                    jTextFieldVacuna.setText(rtaset.getString("vacuna"));
                    jTextFieldCategoria.setText(rtaset.getString("categoria"));
                    jTextFieldCargo.setText(rtaset.getString("cargo"));
                } else {
                    JOptionPane.showMessageDialog(null, "Registro no encontrado");
                }
            }
            catch(SQLException ex) {
                Logger.getLogger(Consumer.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_jButtonConsultarActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        try {
            // TODO add your handling code here:
            actualizarFuncionario(jTextFieldNombres.getText(), jTextFieldApellidos.getText(), jTextFieldEdad.getText(), jTextFieldVacuna.getText(), jTextFieldCategoria.getText(), jTextFieldCargo.getText(), jTextFieldIdentificacion.getText());
            System.out.println("Actualización exitosa!");
        } catch (SQLException ex) {
            Logger.getLogger(ActualizarFuncionario.class.getName()).log(Level.SEVERE, null, ex);
        }

    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ActualizarFuncionario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ActualizarFuncionario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ActualizarFuncionario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ActualizarFuncionario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ActualizarFuncionario().setVisible(true);
            }
        });
    }
    
        private static ConexionDB conex = new ConexionDB();
        public void actualizarFuncionario(String nombres, String apellidos, String edad, String vacuna, String categoria, String cargo, String cedula) throws SQLException {
            conex.establecerconexion();
            String seleccion="UPDATE `funcionario` SET `nombres` = '"+nombres+"', `apellidos` = '"+apellidos+"', `edad` = '"+edad+"', `vacuna` = '"+vacuna+"', `categoria` = '"+categoria+"', `cargo` = '"+cargo+"'  WHERE `funcionario`.`cedula` = '"+cedula+"';";
            PreparedStatement ps = conex.con.prepareStatement(seleccion);
            ps.executeUpdate();
        }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButtonConsultar;
    private javax.swing.JButton jButtonVolver;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabelFondo;
    private javax.swing.JLabel jLabelTitle;
    private javax.swing.JTextField jTextFieldApellidos;
    private javax.swing.JTextField jTextFieldCargo;
    private javax.swing.JTextField jTextFieldCategoria;
    private javax.swing.JTextField jTextFieldEdad;
    private javax.swing.JTextField jTextFieldIdentificacion;
    private javax.swing.JTextField jTextFieldNombres;
    private javax.swing.JTextField jTextFieldVacuna;
    // End of variables declaration//GEN-END:variables
}
