/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Interfaces;

/**
 *
 * @author erick
 */
public class Menu extends javax.swing.JFrame {

    /**
     * Creates new form Menu
     */
    public Menu() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabelHospitalIco = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabelFondo = new javax.swing.JLabel();
        jMenuBar2 = new javax.swing.JMenuBar();
        jMenuRegistrar = new javax.swing.JMenu();
        jMenuItemRegistrarFuncionario = new javax.swing.JMenuItem();
        jMenuItemRegistrarUsuario = new javax.swing.JMenuItem();
        jMenuConsultar = new javax.swing.JMenu();
        jMenuItemConsultarFuncionario = new javax.swing.JMenuItem();
        jMenuItemConsultarUsuario = new javax.swing.JMenuItem();
        jMenuActualizar = new javax.swing.JMenu();
        jMenuItemActualizarFuncionario = new javax.swing.JMenuItem();
        jMenuItemActualizarUsuario = new javax.swing.JMenuItem();
        jMenuGenerarReporteMenu = new javax.swing.JMenu();
        jMenuGenerarReporte = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabelHospitalIco.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/HospitalIco.png"))); // NOI18N
        getContentPane().add(jLabelHospitalIco, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 0, -1, -1));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Bienvenido al Hospital Comunal Las Mercedes");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 170, -1, -1));

        jButton1.setBackground(new java.awt.Color(51, 0, 153));
        jButton1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("Salir");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 210, -1, -1));

        jLabelFondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/BlueWallpaper.png"))); // NOI18N
        getContentPane().add(jLabelFondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 410, 250));

        jMenuRegistrar.setText("Registrar");

        jMenuItemRegistrarFuncionario.setText("Registrar Funcionario");
        jMenuItemRegistrarFuncionario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemRegistrarFuncionarioActionPerformed(evt);
            }
        });
        jMenuRegistrar.add(jMenuItemRegistrarFuncionario);

        jMenuItemRegistrarUsuario.setText("Registrar Usuario");
        jMenuItemRegistrarUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemRegistrarUsuarioActionPerformed(evt);
            }
        });
        jMenuRegistrar.add(jMenuItemRegistrarUsuario);

        jMenuBar2.add(jMenuRegistrar);

        jMenuConsultar.setText("Consultar");

        jMenuItemConsultarFuncionario.setText("Consultar Funcionario");
        jMenuItemConsultarFuncionario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemConsultarFuncionarioActionPerformed(evt);
            }
        });
        jMenuConsultar.add(jMenuItemConsultarFuncionario);

        jMenuItemConsultarUsuario.setText("Consultar Usuario");
        jMenuItemConsultarUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemConsultarUsuarioActionPerformed(evt);
            }
        });
        jMenuConsultar.add(jMenuItemConsultarUsuario);

        jMenuBar2.add(jMenuConsultar);

        jMenuActualizar.setText("Actualizar");

        jMenuItemActualizarFuncionario.setText("Actualizar Funcionario");
        jMenuItemActualizarFuncionario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemActualizarFuncionarioActionPerformed(evt);
            }
        });
        jMenuActualizar.add(jMenuItemActualizarFuncionario);

        jMenuItemActualizarUsuario.setText("Actualizar Usuario");
        jMenuItemActualizarUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemActualizarUsuarioActionPerformed(evt);
            }
        });
        jMenuActualizar.add(jMenuItemActualizarUsuario);

        jMenuBar2.add(jMenuActualizar);

        jMenuGenerarReporteMenu.setText("Generar Reporte");

        jMenuGenerarReporte.setText("Generar Reporte");
        jMenuGenerarReporte.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuGenerarReporteActionPerformed(evt);
            }
        });
        jMenuGenerarReporteMenu.add(jMenuGenerarReporte);

        jMenuBar2.add(jMenuGenerarReporteMenu);

        setJMenuBar(jMenuBar2);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jMenuItemRegistrarFuncionarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemRegistrarFuncionarioActionPerformed
        // TODO add your handling code here:
        this.dispose();
	RegistrarFuncionario registrarFuncionario = new RegistrarFuncionario();
        registrarFuncionario.setVisible(true);
    }//GEN-LAST:event_jMenuItemRegistrarFuncionarioActionPerformed

    private void jMenuItemRegistrarUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemRegistrarUsuarioActionPerformed
        // TODO add your handling code here:
        this.dispose();
	RegistrarUsuario registrarUsuario = new RegistrarUsuario();
        registrarUsuario.setVisible(true);
    }//GEN-LAST:event_jMenuItemRegistrarUsuarioActionPerformed

    private void jMenuItemConsultarFuncionarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemConsultarFuncionarioActionPerformed
        // TODO add your handling code here:
        this.dispose();
	ConsultarFuncionario consultarFuncionario = new ConsultarFuncionario();
        consultarFuncionario.setVisible(true);
    }//GEN-LAST:event_jMenuItemConsultarFuncionarioActionPerformed

    private void jMenuItemConsultarUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemConsultarUsuarioActionPerformed
        // TODO add your handling code here:
        this.dispose();
	ConsultarUsuario consultarUsuario = new ConsultarUsuario();
        consultarUsuario.setVisible(true);
    }//GEN-LAST:event_jMenuItemConsultarUsuarioActionPerformed

    private void jMenuItemActualizarFuncionarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemActualizarFuncionarioActionPerformed
        // TODO add your handling code here:
        this.dispose();
	ActualizarFuncionario actualizarFuncionario = new ActualizarFuncionario();
        actualizarFuncionario.setVisible(true);
    }//GEN-LAST:event_jMenuItemActualizarFuncionarioActionPerformed

    private void jMenuItemActualizarUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemActualizarUsuarioActionPerformed
        // TODO add your handling code here:
        this.dispose();
	ActualizarUsuario actualizarUsuario = new ActualizarUsuario();
        actualizarUsuario.setVisible(true);
    }//GEN-LAST:event_jMenuItemActualizarUsuarioActionPerformed

    private void jMenuGenerarReporteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuGenerarReporteActionPerformed
        // TODO add your handling code here:
        this.dispose();
	GenerarReporte generarReporte = new GenerarReporte();
        generarReporte.setVisible(true);
    }//GEN-LAST:event_jMenuGenerarReporteActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Menu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabelFondo;
    private javax.swing.JLabel jLabelHospitalIco;
    private javax.swing.JMenu jMenuActualizar;
    private javax.swing.JMenuBar jMenuBar2;
    private javax.swing.JMenu jMenuConsultar;
    private javax.swing.JMenuItem jMenuGenerarReporte;
    private javax.swing.JMenu jMenuGenerarReporteMenu;
    private javax.swing.JMenuItem jMenuItemActualizarFuncionario;
    private javax.swing.JMenuItem jMenuItemActualizarUsuario;
    private javax.swing.JMenuItem jMenuItemConsultarFuncionario;
    private javax.swing.JMenuItem jMenuItemConsultarUsuario;
    private javax.swing.JMenuItem jMenuItemRegistrarFuncionario;
    private javax.swing.JMenuItem jMenuItemRegistrarUsuario;
    private javax.swing.JMenu jMenuRegistrar;
    // End of variables declaration//GEN-END:variables
}
